spring.application.name=job-platform
server.port=${PORT:8080}

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://nexthireuser:nexthire%400506@cluster0.pli9hxn.mongodb.net/nexthire?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.uri=mongodb+srv://nexthireuser:nexthire%400506@cluster0.pli9hxn.mongodb.net/nexthire?retryWrites=true&w=majority&appName=Cluster0

test.value=HELLO_MONGO_TEST
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# CORS
spring.web.cors.allowed-origins=*

# Resume
app.resume.base-url=${BACKEND_URL:http://localhost:8080}/api/resume/

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.security=DEBUG

server.error.include-message=always